import type { FC } from "react";
import { useEffect, useState } from "react";
import { useAiSettings } from "../../context/AiSettingsContext";
import { useWorldbook } from "../../context/WorldbookContext";
import { sendChatRequest } from "../../services/aiClient";
import type { ChatSettings } from "./ChatSettingsScreen";

interface MomentsScreenProps {
  onBack: () => void;
  onCharacterAction?: (action: "like" | "comment", momentId: string, content?: string) => void;
  filterChatId?: string; // 可选：只显示特定角色的朋友圈
}

export interface Moment {
  id: string;
  chatId: string; // 发布这条朋友圈的角色ID
  author: string;
  authorAvatar: string;
  content: string;
  images?: string[];
  timestamp: number; // 发布时间戳
  time: string; // 显示时间
  location?: string;
  likes: string[]; // 点赞的用户ID列表（"🧸"表示玩家）
  comments: Comment[];
  autoGenerated?: boolean; // 是否为AI自动生成
}

export interface Comment {
  id: string;
  author: string; // 评论者ID（"🧸"表示玩家）
  content: string;
  replyTo?: string;
  timestamp: number;
}

const MOMENTS_STORAGE_KEY = "miniOtomePhone_moments";
const STORAGE_KEY_PREFIX = "miniOtomePhone_chatSettings_";
const MESSAGES_KEY_PREFIX = "miniOtomePhone_messages_";
const MOMENTS_COVER_KEY = "miniOtomePhone_momentsCover";

// 格式化时间显示
const formatTime = (timestamp: number): string => {
  const now = Date.now();
  const diff = now - timestamp;
  const minutes = Math.floor(diff / (1000 * 60));
  const hours = Math.floor(diff / (1000 * 60 * 60));
  const days = Math.floor(diff / (1000 * 60 * 60 * 24));

  if (minutes < 1) {
    return "刚刚";
  } else if (minutes < 60) {
    return `${minutes}分钟前`;
  } else if (hours < 24) {
    return `${hours}小时前`;
  } else if (days === 1) {
    return "昨天";
  } else if (days < 7) {
    return `${days}天前`;
  } else {
    const date = new Date(timestamp);
    return date.toLocaleDateString("zh-CN", {
      month: "numeric",
      day: "numeric"
    });
  }
};

// 从localStorage读取朋友圈数据
const loadMoments = (): Moment[] => {
  try {
    const stored = window.localStorage.getItem(MOMENTS_STORAGE_KEY);
    if (stored) {
      const moments: Moment[] = JSON.parse(stored);
      // 更新显示时间
      return moments.map((moment) => ({
        ...moment,
        time: formatTime(moment.timestamp)
      }));
    }
  } catch {
    // ignore
  }
  return [];
};

// 保存朋友圈数据到localStorage
const saveMoments = (moments: Moment[]) => {
  try {
    window.localStorage.setItem(MOMENTS_STORAGE_KEY, JSON.stringify(moments));
  } catch {
    // ignore
  }
};

export const MomentsScreen: FC<MomentsScreenProps> = ({ onBack, onCharacterAction, filterChatId }) => {
  const { aiConfig } = useAiSettings();
  const { config: worldbookConfig } = useWorldbook();
  const [moments, setMoments] = useState<Moment[]>(loadMoments());
  const [likedMoments, setLikedMoments] = useState<Set<string>>(new Set());
  const [showPublishModal, setShowPublishModal] = useState(false);
  const [publishContent, setPublishContent] = useState("");
  const [publishImages, setPublishImages] = useState<string[]>([]);
  const [publishLocation, setPublishLocation] = useState("");
  const [publishing, setPublishing] = useState(false);
  const [coverImage, setCoverImage] = useState<string>(() => {
    // 从localStorage读取朋友圈背景
    try {
      if (filterChatId) {
        // 如果是查看特定角色的朋友圈，读取该角色的背景图
        const coverKey = `miniOtomePhone_momentsCover_${filterChatId}`;
        const stored = window.localStorage.getItem(coverKey);
        return stored || "";
      } else {
        // 如果是查看所有朋友圈，读取全局背景图
        const stored = window.localStorage.getItem(MOMENTS_COVER_KEY);
        return stored || "";
      }
    } catch {
      return "";
    }
  });
  const [showCoverEdit, setShowCoverEdit] = useState(false);
  const [generatingMoment, setGeneratingMoment] = useState(false);
  const [characterSignature, setCharacterSignature] = useState<string>("");

  // 定期更新时间显示和监听朋友圈更新
  useEffect(() => {
    const interval = setInterval(() => {
      setMoments((prev) =>
        prev.map((moment) => ({
          ...moment,
          time: formatTime(moment.timestamp)
        }))
      );
    }, 60000); // 每分钟更新一次

    // 监听localStorage变化，刷新朋友圈数据
    const handleStorageChange = () => {
      const updatedMoments = loadMoments();
      setMoments(updatedMoments);
    };

    // 监听storage事件（跨标签页）
    window.addEventListener('storage', handleStorageChange);

    // 定期检查localStorage变化（同标签页内更新）
    const checkInterval = setInterval(() => {
      const currentMoments = loadMoments();
      const currentIds = currentMoments.map(m => m.id).sort().join(',');
      const stateIds = moments.map(m => m.id).sort().join(',');
      if (currentIds !== stateIds) {
        setMoments(currentMoments);
      }
    }, 1000); // 每秒检查一次

    return () => {
      clearInterval(interval);
      clearInterval(checkInterval);
      window.removeEventListener('storage', handleStorageChange);
    };
  }, [moments]);

  // 保存朋友圈数据
  useEffect(() => {
    saveMoments(moments);
  }, [moments]);

  // 保存朋友圈背景
  useEffect(() => {
    try {
      if (filterChatId) {
        // 如果是特定角色的朋友圈，保存到该角色的key
        const coverKey = `miniOtomePhone_momentsCover_${filterChatId}`;
        if (coverImage) {
          window.localStorage.setItem(coverKey, coverImage);
        } else {
          window.localStorage.removeItem(coverKey);
        }
      } else {
        // 如果是全局朋友圈，保存到全局key
        if (coverImage) {
          window.localStorage.setItem(MOMENTS_COVER_KEY, coverImage);
        } else {
          window.localStorage.removeItem(MOMENTS_COVER_KEY);
        }
      }
    } catch {
      // ignore
    }
  }, [coverImage, filterChatId]);

  // 获取角色信息
  const getCharacterInfo = (chatId: string) => {
    try {
      const stored = window.localStorage.getItem(`${STORAGE_KEY_PREFIX}${chatId}`);
      if (stored) {
        const settings: ChatSettings = JSON.parse(stored);
        return {
          name: settings.nickname?.trim() || "他/她",
          avatar: settings.avatar || "",
          emoji: "🩷",
          signature: settings.signature || ""
        };
      }
    } catch {
      // ignore
    }
    // 默认值
    return { name: "他/她", avatar: "", emoji: "🩷", signature: "" };
  };

  // 读取个性签名并监听更新
  useEffect(() => {
    if (!filterChatId) {
      setCharacterSignature("");
      return;
    }

    // 立即读取一次
    const updateSignature = () => {
      try {
        const stored = window.localStorage.getItem(`${STORAGE_KEY_PREFIX}${filterChatId}`);
        if (stored) {
          const settings: ChatSettings = JSON.parse(stored);
          const newSignature = settings.signature || "";
          console.log("读取个性签名:", newSignature, "从chatId:", filterChatId);
          console.log("完整设置对象:", JSON.stringify(settings));
          console.log("设置对象中的signature字段:", settings.signature);
          setCharacterSignature(newSignature);
        } else {
          console.log("未找到个性签名数据，chatId:", filterChatId);
          setCharacterSignature("");
        }
      } catch (e) {
        console.error("读取个性签名失败:", e);
        setCharacterSignature("");
      }
    };

    updateSignature();

    // 监听自定义事件（同标签页内更新）
    const handleSignatureUpdate = (e: Event) => {
      const customEvent = e as CustomEvent<{ chatId: string; signature: string }>;
      if (customEvent.detail?.chatId === filterChatId) {
        const newSignature = customEvent.detail.signature || "";
        console.log("收到个性签名更新事件:", newSignature, "chatId:", filterChatId);
        setCharacterSignature(newSignature);
      }
    };
    window.addEventListener('signatureUpdated', handleSignatureUpdate);

    // 监听storage事件（跨标签页）
    const handleStorageChange = (e: StorageEvent) => {
      if (e.key === `${STORAGE_KEY_PREFIX}${filterChatId}`) {
        console.log("收到storage事件，更新个性签名");
        updateSignature();
      }
    };
    window.addEventListener('storage', handleStorageChange);

    // 定期检查localStorage变化（同标签页内更新，作为备用方案）
    const checkInterval = setInterval(() => {
      updateSignature();
    }, 300); // 每300毫秒检查一次，更频繁

    return () => {
      clearInterval(checkInterval);
      window.removeEventListener('storage', handleStorageChange);
      window.removeEventListener('signatureUpdated', handleSignatureUpdate);
    };
  }, [filterChatId]);

  // 读取聊天记录（最近20轮左右）
  const getRecentChatMessages = (chatId: string): Array<{ from: "me" | "ai"; content: string }> => {
    try {
      const stored = window.localStorage.getItem(`${MESSAGES_KEY_PREFIX}${chatId}`);
      if (stored) {
        const messages: Array<{ from: "me" | "ai"; content: string }> = JSON.parse(stored);
        // 返回最近20条消息（大约10轮对话）
        return messages.slice(-20);
      }
    } catch {
      // ignore
    }
    return [];
  };

  // 获取世界书内容
  const getWorldbookContent = (chatId: string): string => {
    if (!worldbookConfig) {
      return "";
    }

    // 合并全局和应用特定的世界书
    const allEntries = [
      ...(worldbookConfig.global || []),
      ...(worldbookConfig.perApp?.wechat || [])
    ];

    // 获取该角色相关的世界书条目
    const characterName = getCharacterInfo(chatId).name.toLowerCase();
    const relevantEntries = allEntries.filter((entry) => {
      // 检查是否与角色相关
      return entry.entries?.some((item) =>
        item.enabled !== false && (
          item.title.toLowerCase().includes(characterName) ||
          item.content.toLowerCase().includes(characterName) ||
          item.content.toLowerCase().includes(chatId.toLowerCase())
        )
      );
    });

    // 合并世界书内容
    return relevantEntries
      .map((entry) => {
        if (entry.entries && entry.entries.length > 0) {
          return entry.entries
            .filter((item) => item.enabled !== false)
            .map((item) => `[${item.title}]\n${item.content}`)
            .join("\n\n");
        }
        return "";
      })
      .filter(Boolean)
      .join("\n\n");
  };

  // 生成个性签名
  const generateSignature = async (chatId: string): Promise<string> => {
    try {
      const settings = getCharacterSettings(chatId);
      if (!settings) return "";

      const worldbookContent = getWorldbookContent(chatId);
      const recentMessages = getRecentChatMessages(chatId);

      // 构建提示词
      let prompt = `请为这个角色生成一个符合人设的个性签名（朋友圈签名），要求：
1. 简短精炼，不超过20个字
2. 符合角色的身份、性格和聊天风格
3. 可以是心情、态度、座右铭等
4. **重要：必须原创，禁止照搬以下示例，只能参考风格**

参考风格示例（禁止照搬，仅作风格参考）：
- 抽象搞笑版：精神正常，偶尔发疯 / 脑子离家出走，身体原地打工 / 活着就行，别来沾边
- 日常碎碎念版：好好吃饭，慢慢生活 / 摆烂中，偶尔积极 / 快乐加载中…99%
- 摆烂但鲜活版：摸鱼为主，工作为辅 / 躺平不摆烂，佛系不躺赢 / 打工哪有不疯的，硬撑罢了
- 温柔小真实版：日子普通，快乐不普通 / 平安就好，其余随缘 / 慢慢走，总会有光的
- 随性小自在版：不慌不忙，做自己的光 / 我的生活，与你无关 / 随心走，别回头
- 吃货/摆烂混搭版：干饭积极，打工随意 / 脑袋空空，肚子胖胖 / 吃好喝好，长生不老

角色信息：
- 身份：${settings.taIdentity || "未设置"}
- 性别：${settings.taGender || "未设置"}
- 聊天风格：${settings.chatStyle || "未设置"}
- 其他：${settings.taOther || "未设置"}`;

      if (worldbookContent) {
        prompt += `\n\n世界书设定：\n${worldbookContent}`;
      }

      if (recentMessages.length > 0) {
        prompt += `\n\n最近的聊天记录（参考角色的说话风格）：\n`;
        recentMessages.slice(-10).forEach((msg) => {
          prompt += `${msg.from === "me" ? "玩家" : "角色"}: ${msg.content}\n`;
        });
      }

      prompt += `\n\n请只返回个性签名内容，不要包含其他解释文字。`;

      const response = await sendChatRequest(
        aiConfig,
        [{ role: "user", content: prompt }]
      );

      if (response && response.trim()) {
        // 清理响应，只保留签名内容
        const signature = response.trim().replace(/^["']|["']$/g, "").slice(0, 20);
        return signature;
      }
    } catch (error) {
      console.error("生成个性签名失败:", error);
    }
    return "";
  };

  // 获取角色设置
  const getCharacterSettings = (chatId: string): ChatSettings | null => {
    try {
      const stored = window.localStorage.getItem(`${STORAGE_KEY_PREFIX}${chatId}`);
      if (stored) {
        return JSON.parse(stored) as ChatSettings;
      }
    } catch {
      // ignore
    }
    return null;
  };

  // 生成朋友圈
  const handleGenerateMoment = async () => {
    if (!filterChatId || generatingMoment) return;

    setGeneratingMoment(true);
    try {
      const settings = getCharacterSettings(filterChatId);
      if (!settings) {
        alert("无法获取角色信息");
        setGeneratingMoment(false);
        return;
      }

      const worldbookContent = getWorldbookContent(filterChatId);
      const recentMessages = getRecentChatMessages(filterChatId);
      const characterInfo = getCharacterInfo(filterChatId);

      // 读取最新的个性签名（从localStorage直接读取，确保是最新的）
      let signature = characterInfo.signature;
      // 如果localStorage中有更新的签名，使用它
      try {
        const latestStored = window.localStorage.getItem(`${STORAGE_KEY_PREFIX}${filterChatId}`);
        if (latestStored) {
          const latestSettings: ChatSettings = JSON.parse(latestStored);
          if (latestSettings.signature) {
            signature = latestSettings.signature;
            console.log("使用localStorage中的最新个性签名:", signature);
          }
        }
      } catch (e) {
        console.error("读取最新个性签名失败:", e);
      }

      // 如果没有个性签名，先生成一个
      if (!signature) {
        signature = await generateSignature(filterChatId);
        if (signature) {
          // 保存个性签名 - 从localStorage读取最新设置，确保不会覆盖其他字段
          try {
            const latestStored = window.localStorage.getItem(`${STORAGE_KEY_PREFIX}${filterChatId}`);
            let updatedSettings: ChatSettings;

            if (latestStored) {
              // 如果localStorage中有数据，使用它作为基础
              const existingSettings: ChatSettings = JSON.parse(latestStored);
              updatedSettings = {
                ...existingSettings,
                signature // 只更新签名字段
              };
            } else {
              // 如果localStorage中没有，使用settings
              updatedSettings = {
                ...settings,
                signature
              };
            }

            window.localStorage.setItem(
              `${STORAGE_KEY_PREFIX}${filterChatId}`,
              JSON.stringify(updatedSettings)
            );
            setCharacterSignature(signature);
            console.log("生成并保存个性签名:", signature);
          } catch (error) {
            console.error("保存个性签名失败:", error);
          }
        }
      }

      // 构建生成朋友圈的提示词
      let prompt = `请为这个角色生成一条朋友圈动态，要求：
1. 内容要符合角色的身份、性格和聊天风格
2. 可以是日常分享、心情、生活片段等
3. 语言自然，符合朋友圈的表达习惯
4. 长度控制在50字以内
5. 只返回朋友圈内容，不要包含其他解释

角色信息：
- 姓名：${characterInfo.name}
- 身份：${settings.taIdentity || "未设置"}
- 性别：${settings.taGender || "未设置"}
- 聊天风格：${settings.chatStyle || "未设置"}
- 其他：${settings.taOther || "未设置"}`;

      if (worldbookContent) {
        prompt += `\n\n世界书设定：\n${worldbookContent}`;
      }

      if (recentMessages.length > 0) {
        prompt += `\n\n最近的聊天记录（参考角色的说话风格和最近的话题）：\n`;
        recentMessages.forEach((msg) => {
          prompt += `${msg.from === "me" ? "玩家" : "角色"}: ${msg.content}\n`;
        });
      }

      prompt += `\n\n请只返回朋友圈内容，不要包含其他解释文字。`;

      const response = await sendChatRequest(
        aiConfig,
        [{ role: "user", content: prompt }]
      );

      if (response && response.trim()) {
        // 清理响应
        const content = response.trim().replace(/^["']|["']$/g, "");

        // 创建朋友圈动态
        const newMoment: Moment = {
          id: `moment_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`,
          chatId: filterChatId,
          author: characterInfo.name,
          authorAvatar: characterInfo.avatar || characterInfo.emoji,
          content: content,
          timestamp: Date.now(),
          time: formatTime(Date.now()),
          likes: [],
          comments: [],
          autoGenerated: true
        };

        // 保存到朋友圈列表
        const updatedMoments = [...moments, newMoment];
        setMoments(updatedMoments);
        saveMoments(updatedMoments);
      } else {
        alert("生成朋友圈失败，请重试");
      }
    } catch (error) {
      console.error("生成朋友圈失败:", error);
      alert("生成朋友圈失败，请重试");
    } finally {
      setGeneratingMoment(false);
    }
  };

  const handleLike = async (momentId: string) => {
    const moment = moments.find((m) => m.id === momentId);
    if (!moment) return;

    const isLiked = likedMoments.has(momentId);

    setMoments((prev) =>
      prev.map((m) => {
        if (m.id === momentId) {
          if (isLiked) {
            // 取消点赞
            setLikedMoments((prev) => {
              const newSet = new Set(prev);
              newSet.delete(momentId);
              return newSet;
            });
            return {
              ...m,
              likes: m.likes.filter((like) => like !== "🧸")
            };
          } else {
            // 点赞
            setLikedMoments((prev) => new Set(prev).add(momentId));
            const newLikes = [...m.likes, "🧸"];

            // 如果这是角色发布的朋友圈，触发角色反应
            if (m.chatId && m.chatId !== "🧸" && onCharacterAction) {
              onCharacterAction("like", momentId);
            }

            return {
              ...m,
              likes: newLikes
            };
          }
        }
        return m;
      })
    );
  };

  const handleComment = async (momentId: string, content: string) => {
    if (!content.trim()) return;

    const moment = moments.find((m) => m.id === momentId);
    if (!moment) return;

    // 玩家评论按原样发送/保存，不自动追加冒号
    const commentContent = content.trim();

    const newComment: Comment = {
      id: `c${Date.now()}`,
      author: "🧸",
      content: commentContent,
      timestamp: Date.now()
    };

    setMoments((prev) =>
      prev.map((m) => {
        if (m.id === momentId) {
          const updated = {
            ...m,
            comments: [...m.comments, newComment]
          };

          // 如果这是角色发布的朋友圈，触发角色反应
          if (m.chatId && m.chatId !== "🧸" && onCharacterAction) {
            onCharacterAction("comment", momentId, content.trim());
          }

          return updated;
        }
        return m;
      })
    );
  };

  // 发布朋友圈
  const handlePublish = async () => {
    if (!publishContent.trim() && publishImages.length === 0) {
      alert("请输入内容或添加图片");
      return;
    }

    setPublishing(true);
    try {
      const newMoment: Moment = {
        id: `moment_${Date.now()}_${Math.random().toString(36).slice(2, 8)}`,
        chatId: "🧸", // 玩家发布
        author: "我",
        authorAvatar: "🧸",
        content: publishContent.trim(),
        images: publishImages.length > 0 ? publishImages : undefined,
        timestamp: Date.now(),
        time: "刚刚",
        location: publishLocation.trim() || undefined,
        likes: [],
        comments: [],
        autoGenerated: false
      };

      const updatedMoments = [...moments, newMoment];
      setMoments(updatedMoments);
      saveMoments(updatedMoments);

      // 清空表单
      setPublishContent("");
      setPublishImages([]);
      setPublishLocation("");
      setShowPublishModal(false);

      // 通知父组件玩家发布了朋友圈
      if (onCharacterAction) {
        // 延迟触发，让朋友圈先保存
        setTimeout(() => {
          onCharacterAction("comment", newMoment.id, publishContent.trim());
        }, 500);
      }
    } catch (err) {
      console.error("发布朋友圈失败:", err);
      alert("发布失败，请重试");
    } finally {
      setPublishing(false);
    }
  };

  // 处理图片上传
  const handleImageUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const files = e.target.files;
    if (!files) return;

    const newImages: string[] = [];
    const maxImages = 9;
    const remainingSlots = maxImages - publishImages.length;

    Array.from(files).slice(0, remainingSlots).forEach((file) => {
      if (file.size > 5 * 1024 * 1024) {
        alert(`图片 ${file.name} 大小超过5MB，已跳过`);
        return;
      }

      const reader = new FileReader();
      reader.onload = (event) => {
        const result = event.target?.result;
        if (typeof result === "string") {
          newImages.push(result);
          if (newImages.length === Math.min(files.length, remainingSlots)) {
            setPublishImages((prev) => [...prev, ...newImages]);
          }
        }
      };
      reader.readAsDataURL(file);
    });
  };

  // 移除图片
  const handleRemoveImage = (index: number) => {
    setPublishImages((prev) => prev.filter((_, i) => i !== index));
  };

  // 按时间倒序排列，如果指定了 filterChatId，则只显示该角色的朋友圈
  const filteredMoments = filterChatId
    ? moments.filter((m) => m.chatId === filterChatId)
    : moments;
  const sortedMoments = [...filteredMoments].sort((a, b) => b.timestamp - a.timestamp);

  return (
    <div className="wechat-screen moments-screen">
      <header className="wechat-header moments-header">
        <button type="button" className="wechat-back-btn" onClick={onBack}>
          {filterChatId ? "‹ 返回" : "‹ 发现"}
        </button>
        <div className="wechat-title">
          <div className="wechat-title-main">
            {filterChatId ? getCharacterInfo(filterChatId).name + "的朋友圈" : "朋友圈"}
          </div>
        </div>
        {!filterChatId && (
          <button
            type="button"
            className="moments-camera-btn"
            title="发布朋友圈"
            onClick={() => setShowPublishModal(true)}
          >
            📷
          </button>
        )}
        {filterChatId && (
          <button
            type="button"
            className="moments-generate-btn"
            title="生成朋友圈"
            onClick={handleGenerateMoment}
            disabled={generatingMoment}
          >
            {generatingMoment ? "生成中..." : "✨"}
          </button>
        )}
      </header>

      <main className="moments-body">
        {/* 顶部封面和用户信息 */}
        <div className="moments-profile">
          <div
            className="moments-cover"
            onClick={filterChatId ? undefined : () => setShowCoverEdit(true)}
            style={{ cursor: filterChatId ? "default" : "pointer", position: "relative" }}
          >
            <div
              className="moments-cover-image"
              style={{
                backgroundImage: coverImage ? `url(${coverImage})` : undefined,
                backgroundSize: "cover",
                backgroundPosition: "center",
                backgroundRepeat: "no-repeat"
              }}
            >
              {!coverImage && !filterChatId && (
                <div style={{
                  position: "absolute",
                  top: "50%",
                  left: "50%",
                  transform: "translate(-50%, -50%)",
                  fontSize: "14px",
                  color: "rgba(255, 255, 255, 0.7)",
                  textAlign: "center",
                  pointerEvents: "none"
                }}>
                  点击更换背景
                </div>
              )}
            </div>
          </div>
          {/* 用户信息显示在右侧分割线上 */}
          <div className="moments-user-info">
            <div className="moments-user-info-content">
              <div className="moments-user-name">
                {filterChatId
                  ? getCharacterInfo(filterChatId).name
                  : (() => {
                    try {
                      const stored = window.localStorage.getItem("miniOtomePhone_userNickname");
                      return stored || "我";
                    } catch {
                      return "我";
                    }
                  })()
                }
              </div>
              <div className="moments-user-avatar-wrapper">
                <div className="moments-user-avatar">
                  {filterChatId ? (() => {
                    const characterInfo = getCharacterInfo(filterChatId);
                    if (characterInfo.avatar) {
                      return (
                        <img
                          src={characterInfo.avatar}
                          alt={characterInfo.name}
                          style={{
                            width: "100%",
                            height: "100%",
                            objectFit: "cover",
                            borderRadius: "12px"
                          }}
                          onError={(e) => {
                            const target = e.target as HTMLImageElement;
                            target.style.display = "none";
                            const parent = target.parentElement;
                            if (parent && !parent.querySelector("span")) {
                              const span = document.createElement("span");
                              span.textContent = characterInfo.emoji;
                              parent.appendChild(span);
                            }
                          }}
                        />
                      );
                    }
                    return <span>{characterInfo.emoji}</span>;
                  })() : (() => {
                    try {
                      const stored = window.localStorage.getItem("miniOtomePhone_userAvatar");
                      const avatar = stored || "";
                      if (avatar) {
                        return (
                          <img
                            src={avatar}
                            alt="我的头像"
                            style={{
                              width: "100%",
                              height: "100%",
                              objectFit: "cover",
                              borderRadius: "12px"
                            }}
                            onError={(e) => {
                              const target = e.target as HTMLImageElement;
                              target.style.display = "none";
                              const parent = target.parentElement;
                              if (parent && !parent.querySelector("span")) {
                                const span = document.createElement("span");
                                span.textContent = "🧸";
                                parent.appendChild(span);
                              }
                            }}
                          />
                        );
                      }
                    } catch {
                      // ignore
                    }
                    return <span>🧸</span>;
                  })()}
                </div>
                {filterChatId && characterSignature && (
                  <div className="moments-user-signature">
                    {characterSignature}
                  </div>
                )}
              </div>
            </div>
          </div>
        </div>

        {/* 朋友圈动态列表 */}
        <div className="moments-list">
          {sortedMoments.length === 0 ? (
            <div className="moments-empty">
              <div className="moments-empty-text">还没有朋友圈动态</div>
              <div className="moments-empty-hint">
                {filterChatId
                  ? "该角色还没有发布过朋友圈"
                  : "角色会根据聊天内容自动发布朋友圈哦～"
                }
              </div>
            </div>
          ) : (
            sortedMoments.map((moment) => {
              const characterInfo = getCharacterInfo(moment.chatId);
              return (
                <div key={moment.id} className="moments-item">
                  <div className="moments-item-avatar">
                    {characterInfo.avatar ? (
                      <img
                        src={characterInfo.avatar}
                        alt={characterInfo.name}
                        style={{
                          width: "100%",
                          height: "100%",
                          objectFit: "cover",
                          borderRadius: "6px"
                        }}
                        onError={(e) => {
                          // 如果图片加载失败，显示默认emoji
                          const target = e.target as HTMLImageElement;
                          target.style.display = "none";
                          const parent = target.parentElement;
                          if (parent && !parent.querySelector("span")) {
                            const span = document.createElement("span");
                            span.textContent = moment.authorAvatar || characterInfo.emoji;
                            parent.appendChild(span);
                          }
                        }}
                      />
                    ) : (
                      <span>{moment.authorAvatar || characterInfo.emoji}</span>
                    )}
                  </div>
                  <div className="moments-item-content">
                    <div className="moments-item-header">
                      <span className="moments-item-author">{moment.author}</span>
                    </div>
                    <div className="moments-item-text">{moment.content}</div>
                    {moment.images && moment.images.length > 0 && (
                      <div className="moments-item-images">
                        {moment.images.map((img, idx) => (
                          <div key={idx} className="moments-item-image">
                            {img && (img.startsWith("data:") || img.startsWith("http://") || img.startsWith("https://")) ? (
                              <img src={img} alt="" onError={(e) => {
                                const target = e.target as HTMLImageElement;
                                target.style.display = "none";
                              }} />
                            ) : (
                              <div style={{
                                width: "100%",
                                height: "100%",
                                display: "flex",
                                alignItems: "center",
                                justifyContent: "center",
                                background: "#f0f0f0",
                                color: "#999",
                                fontSize: "12px"
                              }}>
                                图片加载失败
                              </div>
                            )}
                          </div>
                        ))}
                      </div>
                    )}
                    <div className="moments-item-meta">
                      <span className="moments-item-time">{moment.time}</span>
                      {moment.location && (
                        <span className="moments-item-location">📍 {moment.location}</span>
                      )}
                    </div>
                    {(moment.likes.length > 0 || moment.comments.length > 0) && (
                      <div className="moments-item-interactions">
                        {moment.likes.length > 0 && (
                          <div className="moments-likes">
                            <span className="moments-likes-icon">❤️</span>
                            <span className="moments-likes-users">
                              {moment.likes.join(" ")}
                            </span>
                          </div>
                        )}
                        {moment.comments.length > 0 && (
                          <div className="moments-comments">
                            {moment.comments.map((comment) => {
                              // 解析评论格式：角色备注 回复 玩家昵称：回复内容
                              const isPlayerComment = comment.author === "🧸";
                              const content = comment.content;

                              // 检查是否是角色回复格式（包含"回复"关键字）
                              const replyMatch = content.match(/^(.+?)\s+回复\s+(.+?)：(.+)$/);

                              if (replyMatch && !isPlayerComment) {
                                // 角色回复格式
                                const [, characterName, playerName, replyContent] = replyMatch;
                                return (
                                  <div key={comment.id} className="moments-comment">
                                    <span className="moments-comment-author">{characterName}</span>
                                    <span className="moments-comment-reply" style={{ color: "#576b95", margin: "0 4px" }}>回复</span>
                                    <span className="moments-comment-author" style={{ marginRight: "4px" }}>{playerName}</span>
                                    <span style={{ marginRight: "4px" }}>：</span>
                                    <span className="moments-comment-content">{replyContent}</span>
                                  </div>
                                );
                              } else {
                                // 普通评论格式（玩家评论或旧格式的角色评论）
                                return (
                                  <div key={comment.id} className="moments-comment">
                                    <span className="moments-comment-author">
                                      {isPlayerComment ? "我" : comment.author}
                                    </span>
                                    {isPlayerComment ? (
                                      <>
                                        {" "}
                                        <span className="moments-comment-content">{content}</span>
                                      </>
                                    ) : (
                                      <>
                                        <span style={{ marginRight: "4px" }}>：</span>
                                        <span className="moments-comment-content">{content}</span>
                                      </>
                                    )}
                                  </div>
                                );
                              }
                            })}
                          </div>
                        )}
                      </div>
                    )}
                    <div className="moments-item-actions">
                      <button
                        type="button"
                        className={`moments-action-btn ${likedMoments.has(moment.id) ? "moments-action-btn-liked" : ""}`}
                        onClick={() => handleLike(moment.id)}
                      >
                        {likedMoments.has(moment.id) ? "❤️ 已赞" : "🤍 赞"}
                      </button>
                      <button
                        type="button"
                        className="moments-action-btn"
                        onClick={() => {
                          const content = prompt("输入评论：");
                          if (content) {
                            handleComment(moment.id, content);
                          }
                        }}
                      >
                        💬 评论
                      </button>
                    </div>
                  </div>
                </div>
              );
            })
          )}
        </div>
      </main>

      {/* 发布朋友圈弹窗 */}
      {showPublishModal && (
        <div className="settings-modal-backdrop" onClick={() => !publishing && setShowPublishModal(false)}>
          <div
            className="settings-modal-card"
            onClick={(e) => e.stopPropagation()}
            style={{ maxWidth: "500px", maxHeight: "80vh", overflowY: "auto" }}
          >
            <div className="settings-modal-title">发布朋友圈</div>
            <div className="settings-modal-message" style={{ padding: "16px 0" }}>
              <div className="settings-field">
                <textarea
                  className="settings-textarea"
                  placeholder="分享你的生活..."
                  value={publishContent}
                  onChange={(e) => setPublishContent(e.target.value)}
                  style={{ minHeight: "120px", fontSize: "15px" }}
                  maxLength={500}
                />
                <div style={{ fontSize: "12px", color: "var(--text-sub)", textAlign: "right", marginTop: "4px" }}>
                  {publishContent.length}/500
                </div>
              </div>

              {/* 图片预览 */}
              {publishImages.length > 0 && (
                <div className="moments-publish-images">
                  {publishImages.map((img, idx) => (
                    <div key={idx} className="moments-publish-image-item">
                      <img src={img} alt={`预览 ${idx + 1}`} />
                      <button
                        type="button"
                        className="moments-publish-image-remove"
                        onClick={() => handleRemoveImage(idx)}
                      >
                        ×
                      </button>
                    </div>
                  ))}
                </div>
              )}

              {/* 添加图片按钮 */}
              {publishImages.length < 9 && (
                <div className="settings-field">
                  <label
                    htmlFor="moments-image-upload"
                    className="soft-icon-btn"
                    style={{
                      display: "inline-block",
                      cursor: "pointer",
                      textAlign: "center",
                      padding: "8px 16px"
                    }}
                  >
                    📷 添加图片 ({publishImages.length}/9)
                  </label>
                  <input
                    id="moments-image-upload"
                    type="file"
                    accept="image/*"
                    multiple
                    style={{ display: "none" }}
                    onChange={handleImageUpload}
                  />
                </div>
              )}

              {/* 位置输入 */}
              <div className="settings-field">
                <input
                  className="settings-input"
                  placeholder="📍 添加位置（可选）"
                  value={publishLocation}
                  onChange={(e) => setPublishLocation(e.target.value)}
                />
              </div>
            </div>
            <div style={{ display: "flex", gap: "8px", marginTop: "12px" }}>
              <button
                type="button"
                className="soft-icon-btn"
                onClick={() => {
                  if (!publishing) {
                    setShowPublishModal(false);
                    setPublishContent("");
                    setPublishImages([]);
                    setPublishLocation("");
                  }
                }}
                disabled={publishing}
                style={{ flex: 1 }}
              >
                取消
              </button>
              <button
                type="button"
                className="primary-pill-btn"
                onClick={handlePublish}
                disabled={publishing || (!publishContent.trim() && publishImages.length === 0)}
                style={{ flex: 1 }}
              >
                {publishing ? "发布中..." : "发布"}
              </button>
            </div>
          </div>
        </div>
      )}

      {/* 更换背景弹窗 */}
      {showCoverEdit && (
        <div className="settings-modal-backdrop" onClick={() => setShowCoverEdit(false)}>
          <div
            className="settings-modal-card"
            onClick={(e) => e.stopPropagation()}
            style={{ maxWidth: "400px" }}
          >
            <div className="settings-modal-title">更换朋友圈背景</div>
            <div className="settings-modal-message" style={{ padding: "16px 0" }}>
              <div className="settings-field">
                <label className="settings-label">背景预览</label>
                <div
                  style={{
                    width: "100%",
                    height: "200px",
                    borderRadius: "12px",
                    overflow: "hidden",
                    background: coverImage
                      ? `url(${coverImage})`
                      : "linear-gradient(135deg, var(--accent-pink-soft), var(--accent-lilac))",
                    backgroundSize: "cover",
                    backgroundPosition: "center",
                    backgroundRepeat: "no-repeat",
                    border: "2px solid rgba(255, 195, 224, 0.5)",
                    marginTop: "8px",
                    position: "relative"
                  }}
                >
                  {!coverImage && (
                    <div style={{
                      width: "100%",
                      height: "100%",
                      display: "flex",
                      alignItems: "center",
                      justifyContent: "center",
                      color: "var(--text-sub)",
                      fontSize: "14px"
                    }}>
                      暂无背景
                    </div>
                  )}
                </div>
              </div>

              <div className="settings-field">
                <label
                  htmlFor="cover-image-upload"
                  className="primary-pill-btn"
                  style={{
                    display: "inline-block",
                    cursor: "pointer",
                    textAlign: "center",
                    padding: "8px 16px",
                    fontSize: "13px",
                    width: "100%",
                    marginTop: "8px"
                  }}
                >
                  选择本地图片
                </label>
                <input
                  id="cover-image-upload"
                  type="file"
                  accept="image/*"
                  style={{ display: "none" }}
                  onChange={(e) => {
                    const file = e.target.files?.[0];
                    if (file) {
                      if (file.size > 5 * 1024 * 1024) {
                        alert("图片大小不能超过5MB");
                        return;
                      }
                      const reader = new FileReader();
                      reader.onload = (event) => {
                        const result = event.target?.result;
                        if (typeof result === "string") {
                          setCoverImage(result);
                        }
                      };
                      reader.readAsDataURL(file);
                    }
                  }}
                />
              </div>

              <div className="settings-field">
                <input
                  className="settings-input"
                  placeholder="或输入图片URL地址"
                  value={coverImage && !coverImage.startsWith("data:") ? coverImage : ""}
                  onChange={(e) => {
                    const url = e.target.value.trim();
                    if (url) {
                      setCoverImage(url);
                    } else {
                      setCoverImage("");
                    }
                  }}
                />
              </div>

              {coverImage && (
                <div className="settings-field">
                  <button
                    type="button"
                    className="soft-icon-btn"
                    onClick={() => setCoverImage("")}
                    style={{ width: "100%" }}
                  >
                    清除背景
                  </button>
                </div>
              )}
            </div>
            <button
              type="button"
              className="primary-pill-btn settings-modal-btn"
              onClick={() => setShowCoverEdit(false)}
            >
              完成
            </button>
          </div>
        </div>
      )}
    </div>
  );
};
